sudo: false
cache:
  directories:
    - vendor/bundle
language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
matrix:
  allow_failures:
    - rvm: 2.4.0 # Currently json.gem fails to build
before_install: gem install bundler
script: bundle exec rake test
